//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laundry.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public class Disc
    {
        [Key]
        public int Id { get; set; }
        public Nullable<System.DateTime> DisDate { get; set; }
        public Nullable<int> DisAmount { get; set; }
        public Nullable<int> Branche { get; set; }
        public bool Allbra { get; set; }
        public bool status { get; set; }
    }
}
